import type { Metadata } from "next";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { ThemeProvider } from "@/components/theme/theme-provider";
import { ThemeStorage } from "@/components/theme/theme-storage";
import { GoeyToaster } from "@/components/ui/goey-toaster";
import { fontVariables } from "@/lib/fonts";
import { cn } from "@/lib/utils";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Brnd App Main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontVariables} bg-sidebar h-full`}
      suppressHydrationWarning
    >
      <ThemeStorage />
      <body className={cn("h-full antialiased")}>
        <NuqsAdapter>
          <ThemeProvider>
            <GoeyToaster position="top-right" />
            {children}
          </ThemeProvider>
        </NuqsAdapter>
        <SpeedInsights />
      </body>
    </html>
  );
}
